spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tms_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: false

app:
  jwt:
    secret: iNa0fyrTACIZxkT2fu9kET4FtF1BJbIviNa0fyrTACIZxkT2fu9kET4FtF1BJbIv

server:
  port: 8080
  error:
    include-stacktrace: never

logging:
  level:
    web: DEBUG


